version: '3'
services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=pwd
      - PGDATA=.docker/data/postgres
    volumes:
      - ./.docker/data/postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
